config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cages#index"
  resources :cages
  resources :employees
end

app/models/animall.rb
class Animall < ApplicationRecord
  belongs_to :cage
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cage.rb
class Cage < ApplicationRecord
  belongs_to :employee
  has_many :animalls
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :cages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cages_controller.rb
class CagesController < ApplicationController

  def index
    @cages = Cage.all()

  end

  def new

  end

  def create

  end

  def show
    @cage = Cage.find(params[:id])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @employees = Employee.all()
  end

  def new
    @employee = Employee.new()

  end

  def create
    @employee = Employee.create(employee_params)

  end


  private
    def employee_params
      params.require(:employee).permit(:name, :salary, :phone_num)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cages/index.html.erb
Cages <br>
____________________________________
<br>
<% @cages.each do |cage| %>

<%=link_to cage.name , cage_path(cage.id)%><br>

<%end%>

app/views/cages/show.html.erb
Cage page <br>_________________________ <br>
<%= @cage.name %><br>
Assigned employee: <%= @cage.employee.name%><br>

occupants: <% @cage.animalls.each do |animal| %>
            <br>  <%=animal.name%><br>

              <%end%>

app/views/employees/index.html.erb
staff report<br>
_________________________________________________
<table style='border:solid black 1px; padding:3px'>
<tr>
<th>Name</th>
<th>Salary</th>
<th>Total Animals cared for</th>
</tr>

<% @employees.each do |employee| %>
<tr>

<td><%= employee.name %></td><br>

<td><%= employee.salary %></td>

</tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>